dtb-$(CONFIG_ARCH_MSM8953) += msm8953-qrd-sku3-vince.dtb
dtb-$(CONFIG_MACH_XIAOMI_MARKW) := msm8953-qrd-sku3-markw.dtb

always	        := $(dtb-y)

subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
