#
# Makefile for the fingerprint drivers.
#

obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_MARKW)	+= goodix_markw/
obj-$(CONFIG_FINGERPRINT_FPC1020_MARKW)		+= fpc_markw/

subdir-ccflags-y := -finline-functions -ftree-vectorize -funroll-loops
